--CREATE DATABASE IF NOT EXISTS DEMO_CICD;

--CRIANDO SCHEMA
CREATE SCHEMA IF NOT EXISTS DEMO_CICD.DEMO;

--CRIANDO TABELA
CREATE TABLE IF NOT EXISTS DEMO_CICD.DEMO.HELLO_WORLD
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
); 

CREATE TABLE IF NOT EXISTS DEMO_CICD.DEMO.HELLO_WORLD2
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
); 
